// require('./define.js');

// /** @type {{current: {hasDev: boolean, deviceInfo: deviceInfo}}} */

// require('../../../../default-intelligence').dcmConfigModel;

/** @type {dataLoggerConfig} */
const config = {
  deviceInfo: {},
  dataLoggerInfo: {
    data_logger_seq: 1,
    data_logger_def_seq: 1,
    main_seq: 1,
    dl_real_id: 'D_PV_1_001',
    dl_id: 'D_PV_001',
    dl_name: 'PV 001',
    m_name: '냉각형 태양광',
    dl_target_code: '001',
    dld_target_name: 'PV',
    dld_target_prefix: 'D_PV',
    serial_number: null,
    connect_info: {
      type: 'socket',
      // type: 'serial',
      subType: 'parser',
      addConfigInfo: { parser: 'readLineParser', option: '\n' },
      baudRate: 9600,
      port: 9001,
      // port: 'COM8',
      host: 'localhost',
    },
    protocol_info: { mainCategory: 'Sensor', subCategory: 'EanPV' },
  },
  nodeList: [
    {
      node_seq: 56,
      node_def_seq: 31,
      node_class_seq: 31,
      data_logger_seq: 31,
      main_seq: 1,
      node_id: 'V_PV_001',
      node_real_id: 'V_PV_1_001',
      node_name: 'PV 전압 001',
      dl_real_id: 'D_PV_1_일반형',
      dl_id: 'D_PV_일반형',
      dl_name: 'PV 일반형',
      data_unit: 'V',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'pvVol',
      nd_target_name: 'PV 전압',
      nd_target_prefix: 'V_PV',
      nd_description: '200W 급',
      nc_target_id: 'vol',
      nc_target_name: '전압',
      nc_description: null,
    },
    {
      node_seq: 58,
      node_def_seq: 32,
      node_class_seq: 32,
      data_logger_seq: 31,
      main_seq: 1,
      node_id: 'A_PV_001',
      node_real_id: 'A_PV_1_001',
      node_name: 'PV 전류 001',
      dl_real_id: 'D_PV_1_일반형',
      dl_id: 'D_PV_일반형',
      dl_name: 'PV 일반형',
      data_unit: 'A',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'pvAmp',
      nd_target_name: 'PV 전류',
      nd_target_prefix: 'A_PV',
      nd_description: '200W 급',
      nc_target_id: 'amp',
      nc_target_name: '전류',
      nc_description: null,
    },
    {
      node_seq: 60,
      node_def_seq: 33,
      node_class_seq: 33,
      data_logger_seq: 31,
      main_seq: 1,
      node_id: 'W_PV_001',
      node_real_id: 'W_PV_1_001',
      node_name: 'PV 출력 001',
      dl_real_id: 'D_PV_1_일반형',
      dl_id: 'D_PV_일반형',
      dl_name: 'PV 일반형',
      data_unit: 'W',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'pvW',
      nd_target_name: 'PV 출력',
      nd_target_prefix: 'W_PV',
      nd_description: '200W 급',
      nc_target_id: 'watt',
      nc_target_name: '출력',
      nc_description: '출력',
    },
    {
      node_seq: 62,
      node_def_seq: 34,
      node_class_seq: 35,
      data_logger_seq: 31,
      main_seq: 1,
      node_id: 'CP_KWH_001',
      node_real_id: 'CP_KWH_1_001',
      node_name: '누적 발전량 001',
      dl_real_id: 'D_PV_1_일반형',
      dl_id: 'D_PV_일반형',
      dl_name: 'PV 일반형',
      data_unit: 'kWh',
      is_sensor: null,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'cumulativePower',
      nd_target_name: '누적 발전량',
      nd_target_prefix: 'CP_KWH',
      nd_description: '200W 급',
      nc_target_id: 'kWh',
      nc_target_name: '발전량',
      nc_description: '출력',
    },
  ],
};
module.exports = config;
